### ISSUE TITLE
Invalid input has less than useful error message

### ISSUE THREAD

**Issue by daurnimator** [aiq/basexx#5]
e.g.

```
$ lua -e 'print(require"basexx".from_base64("`"))'
lua: /usr/share/lua/5.3/basexx.lua:94: attempt to perform arithmetic on a nil value (local 'index')
stack traceback:
    /usr/share/lua/5.3/basexx.lua:94: in function </usr/share/lua/5.3/basexx.lua:88>
    (...tail calls...)
    (command line):1: in main chunk
    [C]: in ?
```

The offending code is:

``` lua
         local index = string.find( alphabet, c )
         table.insert( result, number_to_bit( index - 1, bits ) )
```

Should be simple enough put an `assert` (or early `return` in).

**Comment by aiq** [comment]
hi,

I will update the basexx tomorrow with the following solution:

The function will return the value **nil** and a additional value that shows the reason for the decoding problem. In your example "`".

br,
Alexander

**Comment by aiq** [comment]
Added the functionality.

See https://github.com/aiq/basexx/commit/7e50aea1f408569670d0f57e3eb7e3b9ff8ec449

**Comment by daurnimator** [comment]
Could improve the error messages.
e.g. return `nil, string.format("unexpected character at position %d: %s", pos, char)`

**Comment by aiq** [comment]
The error message topic is something where I don't have that clear opinion.

I unterstand the motivation to get a message, that you can print to the log or output stream, but I don't like that the information(**pos**, **char**) is captured inside a string.

That's why I decided to return just the minimum amount of information. You are able to define your own message. The **pos** value as third return value was in my mind but I decided to return just the **char**, because with `string.find` it is easy to determine the position of the invalid **char** value.

The third possible solution would be to return a table with all the things, but this is for that small function in my opinion over the top.

I know that `from_z85` and `to_z85` return in some cases an number as error object. In that case it is necessary to differ via the type of the error message. I must improve the README add this point.

**Comment by aiq** [comment]
The commit https://github.com/aiq/basexx/commit/2801091ed8122de57bc714b4951c246a539d46ea fixed the problem.
